/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class orbit_JOrbit */

#ifndef _Included_orbit_JOrbit
#define _Included_orbit_JOrbit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     orbit_JOrbit
 * Method:    CreateTrajectory
 * Signature: (DDDDDDDDDDDDDDDDII)V
 */
JNIEXPORT void JNICALL Java_orbit_JOrbit_CreateTrajectory
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
