package orbit.model;

public class orbitJNI {
  static{
	  System.loadLibrary("orbit");
  }
  public final static native void vec_x_set(long jarg1, vec jarg1_, double jarg2);
  public final static native double vec_x_get(long jarg1, vec jarg1_);
  public final static native void vec_y_set(long jarg1, vec jarg1_, double jarg2);
  public final static native double vec_y_get(long jarg1, vec jarg1_);
  public final static native void vec_z_set(long jarg1, vec jarg1_, double jarg2);
  public final static native double vec_z_get(long jarg1, vec jarg1_);
  public final static native long new_vec();
  public final static native void delete_vec(long jarg1);
  public final static native void Rotation_rotationAroundX_set(long jarg1, Rotation jarg1_, double jarg2);
  public final static native double Rotation_rotationAroundX_get(long jarg1, Rotation jarg1_);
  public final static native void Rotation_rotationAroundY_set(long jarg1, Rotation jarg1_, double jarg2);
  public final static native double Rotation_rotationAroundY_get(long jarg1, Rotation jarg1_);
  public final static native void Rotation_rotationAroundZ_set(long jarg1, Rotation jarg1_, double jarg2);
  public final static native double Rotation_rotationAroundZ_get(long jarg1, Rotation jarg1_);
  public final static native long new_Rotation();
  public final static native void delete_Rotation(long jarg1);
  public final static native void ShipPosition_position_set(long jarg1, ShipPosition jarg1_, long jarg2, vec jarg2_);
  public final static native long ShipPosition_position_get(long jarg1, ShipPosition jarg1_);
  public final static native void ShipPosition_orientation_set(long jarg1, ShipPosition jarg1_, long jarg2, vec jarg2_);
  public final static native long ShipPosition_orientation_get(long jarg1, ShipPosition jarg1_);
  public final static native void ShipPosition_speedFirst_set(long jarg1, ShipPosition jarg1_, long jarg2, vec jarg2_);
  public final static native long ShipPosition_speedFirst_get(long jarg1, ShipPosition jarg1_);
  public final static native long new_ShipPosition();
  public final static native void delete_ShipPosition(long jarg1);
  public final static native void PartOfFlightPlan_delayTime_set(long jarg1, PartOfFlightPlan jarg1_, int jarg2);
  public final static native int PartOfFlightPlan_delayTime_get(long jarg1, PartOfFlightPlan jarg1_);
  public final static native void PartOfFlightPlan_impulseValue_set(long jarg1, PartOfFlightPlan jarg1_, double jarg2);
  public final static native double PartOfFlightPlan_impulseValue_get(long jarg1, PartOfFlightPlan jarg1_);
  public final static native void PartOfFlightPlan_rotateValue_set(long jarg1, PartOfFlightPlan jarg1_, long jarg2, Rotation jarg2_);
  public final static native long PartOfFlightPlan_rotateValue_get(long jarg1, PartOfFlightPlan jarg1_);
  public final static native long new_PartOfFlightPlan();
  public final static native void delete_PartOfFlightPlan(long jarg1);
  public final static native void ShipParams_shipEdgeLength_set(long jarg1, ShipParams jarg1_, double jarg2);
  public final static native double ShipParams_shipEdgeLength_get(long jarg1, ShipParams jarg1_);
  public final static native void ShipParams_shipMass_set(long jarg1, ShipParams jarg1_, double jarg2);
  public final static native double ShipParams_shipMass_get(long jarg1, ShipParams jarg1_);
  public final static native void ShipParams_fuelMass_set(long jarg1, ShipParams jarg1_, double jarg2);
  public final static native double ShipParams_fuelMass_get(long jarg1, ShipParams jarg1_);
  public final static native void ShipParams_maxRotation_set(long jarg1, ShipParams jarg1_, long jarg2, Rotation jarg2_);
  public final static native long ShipParams_maxRotation_get(long jarg1, ShipParams jarg1_);
  public final static native void ShipParams_maxFuelUsagePerSec_set(long jarg1, ShipParams jarg1_, double jarg2);
  public final static native double ShipParams_maxFuelUsagePerSec_get(long jarg1, ShipParams jarg1_);
  public final static native void ShipParams_impulsePerFuel_set(long jarg1, ShipParams jarg1_, double jarg2);
  public final static native double ShipParams_impulsePerFuel_get(long jarg1, ShipParams jarg1_);
  public final static native void ShipParams_flightPlan_set(long jarg1, ShipParams jarg1_, long jarg2, vector_of_part_flight_plan jarg2_);
  public final static native long ShipParams_flightPlan_get(long jarg1, ShipParams jarg1_);
  public final static native void ShipParams_maxOverload_set(long jarg1, ShipParams jarg1_, double jarg2);
  public final static native double ShipParams_maxOverload_get(long jarg1, ShipParams jarg1_);
  public final static native void ShipParams_maxHeating_set(long jarg1, ShipParams jarg1_, double jarg2);
  public final static native double ShipParams_maxHeating_get(long jarg1, ShipParams jarg1_);
  public final static native long new_ShipParams();
  public final static native void delete_ShipParams(long jarg1);
  public final static native void Quants_numberOfQuants_set(long jarg1, Quants jarg1_, int jarg2);
  public final static native int Quants_numberOfQuants_get(long jarg1, Quants jarg1_);
  public final static native void Quants_quantSizeOfSec_set(long jarg1, Quants jarg1_, double jarg2);
  public final static native double Quants_quantSizeOfSec_get(long jarg1, Quants jarg1_);
  public final static native long new_Quants();
  public final static native void delete_Quants(long jarg1);
  public final static native void ReturnValues_position_set(long jarg1, ReturnValues jarg1_, long jarg2, vec jarg2_);
  public final static native long ReturnValues_position_get(long jarg1, ReturnValues jarg1_);
  public final static native void ReturnValues_speed_set(long jarg1, ReturnValues jarg1_, long jarg2, vec jarg2_);
  public final static native long ReturnValues_speed_get(long jarg1, ReturnValues jarg1_);
  public final static native long new_ReturnValues();
  public final static native void delete_ReturnValues(long jarg1);
  public final static native long computeFlightPlan(long jarg1, ShipPosition jarg1_, long jarg2, ShipParams jarg2_, long jarg3, Quants jarg3_);
  public final static native long new_vector_of_part_flight_plan__SWIG_0();
  public final static native long new_vector_of_part_flight_plan__SWIG_1(long jarg1);
  public final static native long vector_of_part_flight_plan_size(long jarg1, vector_of_part_flight_plan jarg1_);
  public final static native long vector_of_part_flight_plan_capacity(long jarg1, vector_of_part_flight_plan jarg1_);
  public final static native void vector_of_part_flight_plan_reserve(long jarg1, vector_of_part_flight_plan jarg1_, long jarg2);
  public final static native boolean vector_of_part_flight_plan_isEmpty(long jarg1, vector_of_part_flight_plan jarg1_);
  public final static native void vector_of_part_flight_plan_clear(long jarg1, vector_of_part_flight_plan jarg1_);
  public final static native void vector_of_part_flight_plan_add(long jarg1, vector_of_part_flight_plan jarg1_, long jarg2, PartOfFlightPlan jarg2_);
  public final static native long vector_of_part_flight_plan_get(long jarg1, vector_of_part_flight_plan jarg1_, int jarg2);
  public final static native void vector_of_part_flight_plan_set(long jarg1, vector_of_part_flight_plan jarg1_, int jarg2, long jarg3, PartOfFlightPlan jarg3_);
  public final static native void delete_vector_of_part_flight_plan(long jarg1);
  public final static native long new_vector_of_return_values__SWIG_0();
  public final static native long new_vector_of_return_values__SWIG_1(long jarg1);
  public final static native long vector_of_return_values_size(long jarg1, vector_of_return_values jarg1_);
  public final static native long vector_of_return_values_capacity(long jarg1, vector_of_return_values jarg1_);
  public final static native void vector_of_return_values_reserve(long jarg1, vector_of_return_values jarg1_, long jarg2);
  public final static native boolean vector_of_return_values_isEmpty(long jarg1, vector_of_return_values jarg1_);
  public final static native void vector_of_return_values_clear(long jarg1, vector_of_return_values jarg1_);
  public final static native void vector_of_return_values_add(long jarg1, vector_of_return_values jarg1_, long jarg2, ReturnValues jarg2_);
  public final static native long vector_of_return_values_get(long jarg1, vector_of_return_values jarg1_, int jarg2);
  public final static native void vector_of_return_values_set(long jarg1, vector_of_return_values jarg1_, int jarg2, long jarg3, ReturnValues jarg3_);
  public final static native void delete_vector_of_return_values(long jarg1);
}
