/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package orbit.model;

public class OrbitSimulator {
  public static double getG() {
    return OrbitSimulatorJNI.G_get();
  }

  public static double getEarthMass() {
    return OrbitSimulatorJNI.EarthMass_get();
  }

  public static double getEarthRadius() {
    return OrbitSimulatorJNI.EarthRadius_get();
  }

  public static double getZeroCelsius() {
    return OrbitSimulatorJNI.ZeroCelsius_get();
  }

  public static double getAtmosphereBoundary() {
    return OrbitSimulatorJNI.AtmosphereBoundary_get();
  }

  public static double getSeaLevelAirDensity() {
    return OrbitSimulatorJNI.SeaLevelAirDensity_get();
  }

  public static vector_of_return_values computeFlightPlan(ShipPosition initialPosition, ShipParams shipParams, Quants quants) {
    return new vector_of_return_values(OrbitSimulatorJNI.computeFlightPlan(ShipPosition.getCPtr(initialPosition), initialPosition, ShipParams.getCPtr(shipParams), shipParams, Quants.getCPtr(quants), quants), true);
  }

}
