/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package orbit.model;

public class PartOfFlightPlan {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PartOfFlightPlan(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PartOfFlightPlan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OrbitSimulatorJNI.delete_PartOfFlightPlan(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDelayTime(int value) {
    OrbitSimulatorJNI.PartOfFlightPlan_delayTime_set(swigCPtr, this, value);
  }

  public int getDelayTime() {
    return OrbitSimulatorJNI.PartOfFlightPlan_delayTime_get(swigCPtr, this);
  }

  public void setImpulseValue(double value) {
    OrbitSimulatorJNI.PartOfFlightPlan_impulseValue_set(swigCPtr, this, value);
  }

  public double getImpulseValue() {
    return OrbitSimulatorJNI.PartOfFlightPlan_impulseValue_get(swigCPtr, this);
  }

  public void setRotateValue(Rotation value) {
    OrbitSimulatorJNI.PartOfFlightPlan_rotateValue_set(swigCPtr, this, Rotation.getCPtr(value), value);
  }

  public Rotation getRotateValue() {
    long cPtr = OrbitSimulatorJNI.PartOfFlightPlan_rotateValue_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Rotation(cPtr, false);
  }

  public PartOfFlightPlan() {
    this(OrbitSimulatorJNI.new_PartOfFlightPlan(), true);
  }

}
