/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package orbit.model;

public class Quants {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Quants(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Quants obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OrbitSimulatorJNI.delete_Quants(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumberOfQuants(int value) {
    OrbitSimulatorJNI.Quants_numberOfQuants_set(swigCPtr, this, value);
  }

  public int getNumberOfQuants() {
    return OrbitSimulatorJNI.Quants_numberOfQuants_get(swigCPtr, this);
  }

  public void setQuantSizeOfSec(double value) {
    OrbitSimulatorJNI.Quants_quantSizeOfSec_set(swigCPtr, this, value);
  }

  public double getQuantSizeOfSec() {
    return OrbitSimulatorJNI.Quants_quantSizeOfSec_get(swigCPtr, this);
  }

  public Quants() {
    this(OrbitSimulatorJNI.new_Quants(), true);
  }

}
