/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package orbit.model;

public class Rotation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Rotation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Rotation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OrbitSimulatorJNI.delete_Rotation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRotationAroundX(double value) {
    OrbitSimulatorJNI.Rotation_rotationAroundX_set(swigCPtr, this, value);
  }

  public double getRotationAroundX() {
    return OrbitSimulatorJNI.Rotation_rotationAroundX_get(swigCPtr, this);
  }

  public void setRotationAroundY(double value) {
    OrbitSimulatorJNI.Rotation_rotationAroundY_set(swigCPtr, this, value);
  }

  public double getRotationAroundY() {
    return OrbitSimulatorJNI.Rotation_rotationAroundY_get(swigCPtr, this);
  }

  public void setRotationAroundZ(double value) {
    OrbitSimulatorJNI.Rotation_rotationAroundZ_set(swigCPtr, this, value);
  }

  public double getRotationAroundZ() {
    return OrbitSimulatorJNI.Rotation_rotationAroundZ_get(swigCPtr, this);
  }

  public Rotation() {
    this(OrbitSimulatorJNI.new_Rotation(), true);
  }

}
