/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package orbit.model;

public class ShipPosition {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ShipPosition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShipPosition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OrbitSimulatorJNI.delete_ShipPosition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPosition(vec value) {
    OrbitSimulatorJNI.ShipPosition_position_set(swigCPtr, this, vec.getCPtr(value), value);
  }

  public vec getPosition() {
    long cPtr = OrbitSimulatorJNI.ShipPosition_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vec(cPtr, false);
  }

  public void setOrientation(vec value) {
    OrbitSimulatorJNI.ShipPosition_orientation_set(swigCPtr, this, vec.getCPtr(value), value);
  }

  public vec getOrientation() {
    long cPtr = OrbitSimulatorJNI.ShipPosition_orientation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vec(cPtr, false);
  }

  public void setSpeedFirst(vec value) {
    OrbitSimulatorJNI.ShipPosition_speedFirst_set(swigCPtr, this, vec.getCPtr(value), value);
  }

  public vec getSpeedFirst() {
    long cPtr = OrbitSimulatorJNI.ShipPosition_speedFirst_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vec(cPtr, false);
  }

  public void setMoment(Rotation value) {
    OrbitSimulatorJNI.ShipPosition_moment_set(swigCPtr, this, Rotation.getCPtr(value), value);
  }

  public Rotation getMoment() {
    long cPtr = OrbitSimulatorJNI.ShipPosition_moment_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Rotation(cPtr, false);
  }

  public ShipPosition() {
    this(OrbitSimulatorJNI.new_ShipPosition(), true);
  }

}
