/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package orbit.model;

public class vector_of_return_values {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vector_of_return_values(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vector_of_return_values obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OrbitSimulatorJNI.delete_vector_of_return_values(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector_of_return_values() {
    this(OrbitSimulatorJNI.new_vector_of_return_values__SWIG_0(), true);
  }

  public vector_of_return_values(long n) {
    this(OrbitSimulatorJNI.new_vector_of_return_values__SWIG_1(n), true);
  }

  public long size() {
    return OrbitSimulatorJNI.vector_of_return_values_size(swigCPtr, this);
  }

  public long capacity() {
    return OrbitSimulatorJNI.vector_of_return_values_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    OrbitSimulatorJNI.vector_of_return_values_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return OrbitSimulatorJNI.vector_of_return_values_isEmpty(swigCPtr, this);
  }

  public void clear() {
    OrbitSimulatorJNI.vector_of_return_values_clear(swigCPtr, this);
  }

  public void add(ReturnValues x) {
    OrbitSimulatorJNI.vector_of_return_values_add(swigCPtr, this, ReturnValues.getCPtr(x), x);
  }

  public ReturnValues get(int i) {
    return new ReturnValues(OrbitSimulatorJNI.vector_of_return_values_get(swigCPtr, this, i), false);
  }

  public void set(int i, ReturnValues val) {
    OrbitSimulatorJNI.vector_of_return_values_set(swigCPtr, this, i, ReturnValues.getCPtr(val), val);
  }

}
